name: CICD Deployment in EKS with Monitoring

#on:
#  push:
#    branches:
#      - main
      
permissions:   
  id-token: write
  contents: read
    
jobs:

  terraform:
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit

  build-and-push-frontend:
    needs: terraform
    uses: ./.github/workflows/build-and-push-frontend.yaml
    secrets: inherit

  build-and-push-backend:
    needs: terraform
    uses: ./.github/workflows/build-and-push-backend.yaml
    secrets: inherit

  deploy-to-eks:
    needs: [ build-and-push-frontend, build-and-push-backend ]
    uses: ./.github/workflows/deploy-to-eks.yaml
    secrets: inherit

  observability:
    needs: deploy-to-eks
    uses: ./.github/workflows/observability.yaml
    secrets: inherit
    
