name: CICD Deployment in EKS with Monitoring

on:
  push:
    branches:
      - main
      
permissions:   
  id-token: write
  contents: read
    
jobs:

  terraform:
    uses: ./.github/workflows/terraform.yaml
    secrets: inherit

  build-and-push:
    needs: terraform
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit

  deploy-to-eks:
    needs: build-and-push
    uses: ./.github/workflows/deploy-to-eks.yaml
    secrets: inherit

  observability:
    needs: deploy-to-eks
    uses: ./.github/workflows/observability.yaml
    secrets: inherit
    
